# General
exp_name:default
debug:False

# Data
data_type:conll
train_size:1000000
data_types:conll

# Padding
max_ent_size:35
max_context_size:100
num_docs:100

# Model Params
hidden_size:2000
dp:0.2

# Candidate Generation
num_candidates:128
prop_gen_candidates:0.75

# Trainer Settings
patience:10
num_epochs:50
batch_size:256
num_workers:8
lr:1e-02
wd:1e-04
embs_optim:rmsprop
other_optim:rmsprop
sparse:False
save_every:5
profile:False

# Cuda
use_cuda:True
device:0
